shell = "zsh"

[plugins]

##### defer loading of zsh plugins #####
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"


##### zsh plugins #####
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['defer']

[plugins.zsh-abbr]
github = "olets/zsh-abbr"

[plugins.F-Sy-H]
github = "z-shell/F-Sy-H"

[plugins.zsh-autopair]
github = "hlissner/zsh-autopair"

[plugins.zoxide]
github = "ajeetdsouza/zoxide"
apply = ["defer"]

[plugins.custom]
local = "~/.config/zsh/plugins"
use = [
    "tools.zsh",
    "alias.plugin.zsh",
    "abbr.zsh",
]
apply = ["defer"]


##### zsh themes #####
[plugins.starship]
inline = 'eval "$(starship init zsh)"'


##### other tools  #####
[plugins.mise]
inline = """
eval "$(mise activate zsh --shims)"
## Mise
export MISE_PYTHON_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/mise/default-python-packages"
export MISE_NODE_DEFAULT_PACKAGES_FILE="$XDG_CONFIG_HOME/mise/default-npm-packages"
"""

[plugins.sdkman]
inline = 'export SDKMAN_DIR="$XDG_DATA_HOME/sdkman" && source "$SDKMAN_DIR/bin/sdkman-init.sh"'

[plugins.atuin]
inline = 'eval "$(atuin init zsh --disable-up-arrow)"'

[plugins.rye]
inline = 'eval "$(rye self completion -s zsh)"'
